CREATE TABLE movies2 (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	price REAL NOT NULL,
	rating INT NOT NULL
);

INSERT INTO movies2 (TITLE, PRICE, RATING)
VALUES ('WONDER WOMAN', 45, 5);
INSERT INTO movies2 (TITLE, PRICE, RATING)
VALUES ('FINDING SHULI', 135, 4);
INSERT INTO movies2 (TITLE, PRICE, RATING)
VALUES ('SPCAE JAM', 44, 3);
INSERT INTO movies2 (TITLE, PRICE, RATING)
VALUES ('FAST AND FURIOUS 9', 98, 4);
INSERT INTO movies2 (TITLE, PRICE, RATING)
VALUES ('BLACK WIDOW', 70, 5);