CREATE TABLE PRODUCTS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	TITLE TEXT NOT NULL,
	PRICE REAL NOT NULL,
	RATING INT NOT NULL
);

INSERT INTO PRODUCTS (TITLE, PRICE, RATING)
VALUES ('WONDER WOMAN', 45, 5);
INSERT INTO PRODUCTS (TITLE, PRICE, RATING)
VALUES ('FINDING SHULI', 135, 4);
INSERT INTO PRODUCTS (TITLE, PRICE, RATING)
VALUES ('SPCAE JAM', 44, 3);
INSERT INTO PRODUCTS (TITLE, PRICE, RATING)
VALUES ('FAST AND FURIOUS 9', 98, 4);
INSERT INTO PRODUCTS (TITLE, PRICE, RATING)
VALUES ('BLACK WIDOW', 70, 5);